### ISSUE TITLE
"The function '/subscriptions/.../.../.../providers/Microsoft.Web/sites/.../functions/PShredder' could not be found."

### ISSUE THREAD

**Issue by Dubl** [ml-systems/nfldb#3]
Hi @margareeman
I would say the first thing to do would be to delete the resource group and then just start over. 

(you can delete the resource group by going into the portal, clicking on resource groups, and clicking the three dots to the right of your resource group you want to delete)

after you deploy again, you can look at a log of your deployment operations to see errors, for more info. 

issue the command below, replacing the "yourresourcegroupname" with your resource group name:

az group deployment operation list --name=NFLDBDeployment --resource-group=yourresouregroupname

I will say that the biggest issue we're noticing is that many names need to be unique across Azure, and this code isn't checking for uniqueness, so so far the only way to know if you came up with a non-unique name is to run the deployment and see if something kicks out. It should tell you in the CLI.

as for the 'setupsqldb' logic app.. it's a bit of vestigial code. Needs to be removed. It used to be the way we set up the schema, but now we just download it via the code.

**Comment by MargareeMan** [comment]
@Dubl 

I deleted the resource group, changed names and redeployed.  The deployment appeared to be successful, as the GameDayData_PFunction_Schedule2 logic app appears in the resourcse group.  However it fails when it runs.  The schedule is loaded in the nfldb and accessible via SSMS, but the game data does not load (due to GameDayData_PFunction_Schedule2 failing.

I have deleted the resource group again and will rerun the deployment.  This time I will redirect the command output to a file so that I can download the result.  At the end of the last deployment I received the following message:

"Downloaded NFLDB Schema 
Deploying NFLDB Schema to nfldb 
VERBOSE: The module 'InitiateNFLDB' depends on the missing object ' NFLDB. BuildFranchise' .  The module will still be created; however, it cannot run successfully until the object exists. 
NFLDB Schema Deployment Completed 
VERBOSE: [nfldb] . [Franchise] rows affected by MERGE: 32 
Initiated 
Blob Storage Path Added to nfldb 
Schedule Load Started "

Also, when I ran the az group deployment operation list command, all items listed (45 items) were provisioningOperation Created or Action with provisioningState "Succeeded".

I tried changing the year in LoadNFLSchedule and running it.  It did not populate nfldb with the 2018 schedule.

If it is useful for you, I will try a couple of more iterations and report back.

In passing, is the myfunctionapp parameter just creating a stub for other code?  I am supplying a name; but I am not connecting it to any code.

**Comment by Dubl** [comment]
Ok. I think it deployed correctly, and this is just an issue with the logic apps. When ypu delete and try again, check if the ‘LoadNFL schedule’ logic app ran. Bringing it up see a history of runs. If a run succeeded, great. If not, run it. If it hasnt run, the ‘gamedaydata_pfunction_schedule2’ logic app wont work, as it has no games. If you bring that one up and see that it has a failed run dont worry. Just kick it off and it should work. And the ‘myfunctionapp’ parameter is a name for the function app. If you look at that, you’ll see it has a python function it in-pshredder

**Comment by MargareeMan** [comment]
I redeployed and ran the ‘LoadNFL schedule’ logic app.  It ran successfully.  The [NFLDB].[Schedule] and [MasterNFL].[Schedule] tables are populated with 321 records; but the [NFLDB].[Game] and [MasterNFL].[game] tables are empty.  I ran GameDayData_PFunction_Schedule2 and it failed.  I added Saturday to the recurrence code in the schedule GameDayData_PFunction_Schedule2 and ran it.  It is now running.  On the half-hour it updated several tables in the database ([NFLDB].[Game], [NFLDB].[Drive], [MasterNFL].[playplayer]).  The [Reference].[player] table is empty, as are others.  

So this is interesting but, as yet, quite opaque.  I will spend some more time trying to understand the architecture and functional aspects of the implementation.  I think that I can see that the structure of the db tables has a more direct relationship to the json feed.  I do not see any aggregation of statistics by player or play -- but then I have not yet explored enough.  I clearly do not understand what the view tables are doing.  It is mostly beyond me.  But thank you for an interesting adaptation of nfldb!

**Comment by Dubl** [comment]
You did it. Awesome. Thanks so much for slugging through, it will help us make it cleaner to run. We’ll follow through on the walk-through that goes into the concepts. And yes, so far we just took clean cuts of the NFL api in the Master tables. I honestly forget all the aggregate views we do (or don’t) have..

**Comment by MargareeMan** [comment]
Impressive stuff!  I will keep a watch out for more docs.  It is mostly over my head, but that does not mean that I cannot value what you have done and are doing.  It is embarrassing, but I only now noticed shredder.py.  I am Mathematica user, so I used the Wolfram Language's ability to handle hierarchical data to parse the json files.  It works for a putzer like me; but it makes me want to try your python code.

**Comment by MargareeMan** [comment]
I have now run GameDayData_PFunction_Schedule2 after changing the year parameter both it and LoadNFLSchedule.  On a quick glance at the game table via SSMS, it does get the games from that year.  The Azure interface, especially the Logic App designer is very slick.  The graphic display of the logic and the dynamic display of the progress and content of the app is very impressive.  Thank you for introducing me to this.

**Comment by Dubl** [comment]
no problem. thanks so much for being the first to get it to work, and for the feedback that'll help us make the deploy cleaner. We'll be adding more, like player info, aggregate views, and PowerBI reports
